export default {
    HARVEST: 'HARVEST',
    TRANSFER: 'TRANSFER',
    WITHDRAW: 'WITHDRAW',
    PICKUP: 'PICKUP',
    BUILD: 'BUILD',
    UPGRADE: 'UPGRADE',
    ATTACK: 'ATTACK',
    RESERVE: 'RESERVE',
    MOVE_TO: 'MOVE_TO'
};
